lingua = 'it'

preventivo = "Preventivo per mattoni etc etc 1234567891"

cliente = """
Mario Rossi
Electric Boogaloo
Via Abc Roma
Tel 0123456789
C.F. ABC123DEF456
"""

[tab]
iva = 10
nota = "IVA ridotta etc etc"

[[tab.riga]]
#mq = 100
pz = 390*3
eur = 1
um = 'pz'
kg-pz = 1
img = "default.jpg"
desc = 'Art. 100'

[[tab.riga]]
mq = 30
eur = 50

---

Note del preventivo

$caratteristiche